project:
  name: qs-workshop
  regions:
  - ap-southeast-1
  - us-east-1
  - us-west-2
  - eu-central-1
tests:
  default:
    template: ./templates/master.template.yaml
    regions:
    - us-west-1
